version: 1.0.{build}

clone_script:
  - cmd: git clone --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%

platform:
  - x64

configuration:
  - Debug

build_script:
  - ps: |
      msbuild vs/odbc64.sln

deploy_script:
   - ps: |
       Push-AppveyorArtifact "vs\installer64\bin\Debug\clickhouse_odbc_x64.msi"
